export { FireTab } from "./FireTab"
export { SchoolFeesTab } from "./SchoolFeesTab"
export { GraduationTab } from "./GraduationTab"
export { MarriageTab } from "./MarriageTab"
export { HouseTab } from "./HouseTab"
export { WhitegoodsTab } from "./WhitegoodsTab"
export { CustomTab } from "./CustomTab"
export { GOAL_TAB_CONFIG } from "./constants/GoalTabs.constants"
export type { TabProps } from "./types/GoalTabs.types"
