import type { DashboardView } from "@/types/dashboard"

export const MOCK_DASHBOARD: DashboardView = {
  netWorth: {
    total: "₹1,52,40,000",
    calculatedAt: new Date().toISOString(),
    missingNavCount: 0,
    breakdown: [
      { label: "MF portfolio", value: "₹82.4 L" },
      { label: "EPF + NPS", value: "₹37.1 L" },
      { label: "Gold", value: "₹8.2 L" },
      { label: "Emergency", value: "₹14.0 L" },
    ],
  },
  fire: null,
  sips: {
    totalAmount: "₹45,000",
    sipCount: 5,
    pendingCount: 1,
    items: [
      { label: "FIRE · PPFAS Flexi Cap", amount: "₹20,000", status: "processed", dotColor: "#2D8A50" },
      { label: "FIRE · Axis Nifty 100", amount: "₹10,000", status: "pending", dotColor: "#60A5FA" },
      { label: "Reyaansh Grad", amount: "₹8,000", status: "processed", dotColor: "#A78BFA" },
      { label: "Kid2 Grad", amount: "₹7,000", status: "processed", dotColor: "#FB923C" },
    ],
    closedTotalAmount: "₹0",
    closedCount: 0,
    closedItems: [],
  },
  allocation: {
    equityPercent: 62,
    segments: [
      { label: "Large cap", percent: 39, color: "#2D8A50" },
      { label: "Mid cap", percent: 14, color: "#2563EB" },
      { label: "Small cap", percent: 9, color: "#EA580C" },
      { label: "International", percent: 5, color: "#7C3AED" },
      { label: "Debt + Gold", percent: 24, color: "#64748B" },
    ],
  },
  goals: [
    {
      id: "fire",
      icon: "🔥",
      name: "FIRE",
      status: "monitor",
      targetLabel: "Target ₹5.0 Cr · Age 45",
      currentValue: "₹36.2 L",
      progressPercent: 7.2,
      gap: "Gap ₹4.64 Cr",
      borderColor: "#2D8A50",
      iconBg: "#E8F5E9",
    },
    {
      id: "school",
      icon: "🏫",
      name: "R. School",
      status: "on-track",
      targetLabel: "Target ₹19 L · 2036",
      currentValue: "₹11.8 L",
      progressPercent: 62,
      gap: "Gap ₹7.2 L",
      borderColor: "#7B3FA0",
      iconBg: "#F5EEF8",
    },
    {
      id: "grad",
      icon: "🎓",
      name: "R. Grad",
      status: "on-track",
      targetLabel: "Target ₹53.9 L · 2037",
      currentValue: "₹14.1 L",
      progressPercent: 26,
      gap: "Gap ₹39.8 L",
      borderColor: "#C87820",
      iconBg: "#EFF6FF",
    },
  ],
}
