export { computeEducationForYear } from "./education"
export { computeMarriageForYear } from "./marriage"
export { computeWhitegoodsForYear } from "./whitegoods"
export { computeTravelForYear } from "./travel"
export { computeHealthcareForYear } from "./healthcare"
export { computeLivingExpenseForYear } from "./living-expense"
